name: stocker-backend
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - "uvicorn[standard]"
      - sqlalchemy
      - pymysql
      - pydantic-settings
      - python-dotenv
      - pytest
      - pyjwt
      - "pwdlib[argon2]"
      - python-multipart
      - email-validator
      - httpx